name: Go [Cross]

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

  schedule:
    - cron: '*/10 * * * *'

concurrency:
  group: go_cross
  cancel-in-progress: true

jobs:
  cross_platform:
    strategy:
      max-parallel: 3 #cpu cores /- runner
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ] # multiple OS versions
        go-version: [ '1.19.x', '1.20.x' ] # multiple Go versions #sync.atomic supported only in 1.19
        arch: [x64, arm, arm64]

    runs-on: ${{ matrix.os }}
    #concurrency: 8 # no of runners
    env:
      GOCACHE: /tmp/go/gocache

    steps:
      - uses: actions/checkout@v3

      - name: Cache Go modules and tests
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod/cache
            /tmp/go/gocache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod','imageslicer_test.go') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.mod','imageslicer_test.go') }}

      - name: Set up Go ${{ matrix.go-version }} ${{runner.os}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test Short
        run: go test -v -run="^Test" -short ./...

#      - name: Test
#        run: go test -v -run="^Test" ./... -timeout 6h


#      - name: Test Intensive Retry
#        uses: nick-fields/retry@v2
#        with:
#          max_attempts: 3
#          retry_on: error
#          timeout_minutes: 120m
#          #working-directory: ${{ github.workspace }}
#          command: |
#            echo 'go test'
#            echo $pwd
#
#            go test -v -run=^Test ./... -timeout 120m


#      - name: Test Intensive Cross Platform
#        run: go test -v -run=^Test ./... -timeout 360m


#    https://github.com/marketplace/actions/retry-step