# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Fuzz

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

  schedule:
    - cron: '* */1 * * *'

concurrency:
  group: go_fuzz
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOCACHE: /tmp/go/gocache

    steps:
    - uses: actions/checkout@v3

    - name: Cache Go modules and tests
      uses: actions/cache@v2
      with:
        path: |
         ~/go/pkg/mod/cache
         /tmp/go/gocache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod','imageslicer_test.go') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.mod','imageslicer_test.go') }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

  fuzz:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fuzz Short
        run: go test -run="^Fuzz" -short -v -timeout 360m -fuzztime 1m

  race-fuzz:
    runs-on: ubuntu-latest
    needs: [ fuzz ]
    steps:
      - uses: actions/checkout@v3

      - name: Race Fuzz
        run: go test ./... -v -race -run "^Fuzz"  -timeout 360m -fuzztime 1m
        continue-on-error: true

      - name: Race Short Fuzz
        run: go test -v -race -run="^Fuzz"  -short ./... -timeout 360m -fuzztime 1m

  fuzz-intensive:
    runs-on: ubuntu-latest
    needs: [ fuzz ]

    steps:
      - uses: actions/checkout@v3

      - name: Fuzz
        run: go test -run="^Fuzz" -v -timeout 360m -fuzztime 1m
        continue-on-error: true

      - name: Test Intensive Retry
        uses: nick-fields/retry@v2
        with:
          max_attempts: 10
          retry_on: error
          timeout_minutes: 360m
          #working-directory: ${{ github.workspace }}
          command: |
            echo "go fuzz intensive failed"









